[41기 류건호] [ADD]: 휴대전화 번호 인증 NAVER SENS를 이용해 완료
wecode-bootcamp-korea/41-2nd-CalPick-backend pull request #11
Opened 2023-02-07 01:06 UTC by kakao513

SMS 엔드포인트 작성중 CryptoJS 설치를 위해 변경

[ADD]: SMS 인증 엔드포인트 구현 휴대전화를 받으면 코드를 보내고 인증번호를 입력후 비교 후 검증 엔드포인트 네이버 문제로 인해 내일까지 실행결과는 지켜봐야함

[ADD]: NAVER SENS API 구현 완료

[ADD]: 문자인증 API 구현 완료

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 네이버 센스를 이용한 문자인증 시스템 구성
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 랜덤한 6개 수 생성 후 사용자의 휴대폰에 전송
- 그 후 인증코드 비교후 맞을 경우 승인 아닐 경우 비승인

<br />

<br />

2023-02-07 03:58 UTC, bigfanoftim requested changes

2023-02-07 03:58 UTC, bigfanoftim commented on src/services/verificationService.js
> +	// const message = await sendSMS("01091863261", verificationCode);
번호는 환경변수로 관리해주세요.

2023-02-07 03:58 UTC, bigfanoftim commented on src/services/verificationService.js
> +	if (data === undefined || data.length === 0) detectError("다시 입력해주세요", 404);
404가 맞는 status code인지 고민해보시면 좋을 것 같습니다.
보통 요청에 맞는 주소가 없을 경우 사용됩니다.

2023-02-08 03:43 UTC, kakao513 commented on src/services/verificationService.js
> +	// const message = await sendSMS("01091863261", verificationCode);
환경변수로 관리 완료했습니다 :)

2023-02-08 03:43 UTC, kakao513 commented on src/services/verificationService.js
> +	if (data === undefined || data.length === 0) detectError("다시 입력해주세요", 404);
이 부분은 403으로 변경했습니다.

2023-02-08 05:34 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-08 05:34 UTC, bigfanoftim commented on src/services/util/naverSMS.js
> +	hmac.update(ACCESS_KEY);
음 이 부분은 cryptojs에서 지원하는 메소드 체이닝 방식이나 다른 방식이 있을 것 같은데 ㅎㅎ
다음에 한번 파악해보시면 좋을 것 같네요!

2023-02-08 05:34 UTC, merged