[41기 류건호] ADD: 시험장 장소 및 좌석 응시 정보 엔드포인트 구현
wecode-bootcamp-korea/41-2nd-CalPick-backend pull request #12
Opened 2023-02-07 01:10 UTC by kakao513

[ADD]: 시험장 필터링 기능 완료 쿼리빌더를 통해 쿼리 파라미터가 들어올시 동적으로 쿼리 생성 가능

[ADD]: 시험장 선택 후 좌석 선택 조건과 좌석 맵 제공 API 구현 완료

[FIX]: index routes 에 난 conflict 해결을 위해 reset을 한 다음 해결 진행

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 쿼리 파라미터를 이용해서 데이터를 변경해서 보여줌

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 호출하는 데이터가 달라서 쿼리 파라미터를 사용하지 않고 엔드포인트를 각각 설정해 주어야 했지만 일단 기능은 구현이 되기 때문에 고치는 시간과 다른 기능을 만드는 trade off 를 비교해 본 결과 기술 부채를 인정하고 넘어가는 것이 현재 프로젝트 내에서는 더 합리적이라고 판단

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-07 04:39 UTC, bigfanoftim requested changes

2023-02-07 04:39 UTC, bigfanoftim commented on src/models/testsitesModels.js
> +	// const { whereClause, selectClause, joinClause, groupByClause } = test.buildQuery();
불필요한 주석은 지워주세요! 필요한 기능이면 코드로 제대로 작성해주시고
질문이 있으시면 질문을 남겨주세요! 상황에 대한 공유가 더 진행되면 좋겠습니다~

2023-02-08 05:36 UTC, bigfanoftim requested changes

2023-02-08 05:36 UTC, bigfanoftim commented on src/services/util/seatMaper.js
> +}
불필요한 줄바꿈들은 지워주세요!

2023-02-08 06:56 UTC, kakao513 commented on src/models/testsitesModels.js
> +	// const { whereClause, selectClause, joinClause, groupByClause } = test.buildQuery();
넵넵 감사합니다 :)

2023-02-08 06:56 UTC, kakao513 commented on src/services/util/seatMaper.js
> +}
넵넵 수정 완료했습니다

2023-02-08 08:46 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-08 08:46 UTC, merged