[41기 류건호] FIX: 데이터베이스 구조 변경 데이터에 논리적인 결함 발견후 구조 변경
wecode-bootcamp-korea/41-2nd-CalPick-backend pull request #8
Opened 2023-02-03 02:24 UTC by kakao513

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [x] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 데이터베이스 구조 변경 및 컬럼 추가 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 더 쉽게 데이터를 인출하기 위해서 데이터베이스를 수정하였습니다. 서브 쿼리를 만들어서 해보려고도 하였으나 작업의 효용성과 서브 쿼리를 날렸을 때 짜여질 쿼리문을 생각해본 결과 이 작업이 더 좋다고 생각하여 바꿨습니다.

<br />

2023-02-03 05:05 UTC, bigfanoftim requested changes

2023-02-03 05:05 UTC, bigfanoftim commented on db/migrations/20230203003939_upate_tests_table.sql
> +SET FOREIGN_KEY_CHECKS = 0;
다시 1로 변경해주어야 하지 않나요??

2023-02-05 08:10 UTC, kakao513 commented on db/migrations/20230203003939_upate_tests_table.sql
> +SET FOREIGN_KEY_CHECKS = 0;
넵 밑에 수정했습니다

2023-02-05 08:12 UTC, kakao513 commented
호준님 혹시 merge 시켜주실 때 axios branch를 먼저 merge 시켜 주실 수 있으실까요? 그게 해결되면 다시 local 에 있는 main update한 다음에 여기에 반영하면 커밋 메시지 1개만 있을 수 있을 것 같습니다.

2023-02-06 01:23 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-06 02:50 UTC, merged